name: Deploy Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  initialize:
    name: initialize
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag}}
    steps:
      - uses: actions/checkout@v4
      - name: Generate Tag
        id: meta
        run: |
          TAG="v${GITHUB_RUN_NUMBER}-$(echo $GITHUB_SHA | cut -c1-7)"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
  restore:
    name: Restore
    runs-on: ubuntu-latest
    needs: initialize
    steps:
      - uses: actions/checkout@v4
        name: Setup .Net Core
      - uses: actions/setup-dotnet@v4
        with:
          dontnet-version: "10.0.x"
      - name: Restore Dependencies
        run: dotnet restore
  build:
    name: Build dependcies
    runs-on: ubuntu-latest
    needs: restore
    steps:
      - uses: actions/checkout@v4
        name: Setup .Net Core
      - uses: actions/setup-dotnet@v4
        with:
          dontnet-version: "10.0.x"
      - name: Build Project
        run: dotnet build --configuration Release
  unit_tests:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        name: Setup .Net Core
      - uses: actions/setup-dotnet@v4
        with:
          dontnet-version: "10.0.x"
      - name: Run Test
        run: dotnet  test --configuration Release --verbosity normal
  fs_scan:
    name: FS Scan
    runs-on: ubuntu-latest
    needs: unit_tests
    permissions:
      security-events: write
    steps:
      - name: Chekout Code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-fs.sarif"
          exit-code: 0
          severity: "HIGH,CRITICAL"
      - name: Upload Trivy FS SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-fs.sarif"
          category: "trivy-fs-scan"
  docker_build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: ["initialize", "build", "unit_tests", "fs_scan"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build And Export
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: employees-management-system:${{ needs.initialize.outputs.tag }}
          outputs: type=docker,dest=/tmp/image.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/image.tar
  smoke_test:
    name: Running Smoke Test
    runs-on: ubuntu-latest
    needs: ["initialize", "fs_scan", "docker_build"]
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp
      - name: Load Docker Image
        run: docker load --input /tmp/image.tar
      - name: Start Service
        env:
          IMAGE_TAG: ${{ needs.initialize.outputs.tag }}
        run: |
          sed -i 's/build: ./# build: ./' docker-compose.yml
          sed -i "s/image: employees-management-system:latest/image: employees-management-system:${IMAGE_TAG}/" docker-compose.yml
          docker compose up -d
      - name: Wait for services to be ready
        run: |
          timeout 30s bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080)" != "200" && "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080)" != "302" && "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080)" != "404" ]]; do sleep 2; done'
      - name: Verify Web Service
        run: docker compose ps
      - name: Dump docker logs on failure
        if: failure()
        run: docker compose logs
      - name: Stop Service
        if: always()
        run: docker compose down -v
  trivy_image:
    name: Image Scan With Trivy
    needs: ["initialize", "smoke_test"]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp
      - name: Load Image
        run: docker load --input /tmp/image.tar
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "employees-management-system:${{ needs.initialize.outputs.tag }}"
          format: "table"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
  grype_scan:
    name: Grype Image Scan
    needs: ["initialize", "trivy_image"]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp
      - name: Docker Load Image
        run: docker load --input /tmp/image.tar
      - name: Run Grype scanner
        uses: anchore/scan-action@v3
        with:
          image: employees-management-system:${{ needs.initialize.outputs.tag }}
          fail-build: false
  generate_sbom:
    name: Generate Sbom
    needs: ["initialize", "trivy_image", "grype_scan"]
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/image.tar
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: employees-management-system:${{ needs.initialize.outputs.tag }}
          format: spdx-json
          output-file: sbom.spdx.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
  docker_push:
    name: Docker Image Push
    runs-on: ubuntu-latest
    needs:
      [
        "initialize",
        "docker_build",
        "trivy_image",
        "grype_scan",
        "generate_sbom",
      ]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp
      - name: Docker Load Image
        run: docker load --input /tmp/image.tar
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: |
          docker tag employees-management-system:${{ needs.initialize.outputs.tag }} ${{ secrets.DOCKERHUB_USERNAME }}/employees-management-system:${{ needs.initialize.outputs.tag }}
          docker push ${{ vars.DOCKERHUB_USERNAME }}/employees-management-system:${{ needs.initialize.outputs.tag }}
