name: Deploy Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  initialize:
    name: initialize
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.output.tag}}
    steps:
      - uses: actions/checkout@v4
      - name: Generate Tag
        run: |
          TAG="v${GITHUB_RUN_NUMBER}-$(echo $GITHUB_SHA | cut -c1-7)"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
  restore:
    name: Restore
    runs-on: ubuntu-latest
    needs: initialize
    steps:
      - uses: actions/checkout@v4
        name: Setup .Net Core
      - uses: actions/setup-dotnet@v4
        with:
          dontnet-version: "10.0.x"
      - name: Restore Dependencies
        run: dotnet restore
  build:
    name: Build dependcies
    runs-on: ubuntu-latest
    needs: restore
    steps:
      - uses: actions/checkout@v4
        name: Setup .Net Core
      - uses: actions/setup-dotnet@v4
        with:
          dontnet-version: "10.0.x"
      - name: Build Project
        run: dotnet build --configuration Release
  unit_tests:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        name: Setup .Net Core
      - uses: actions/setup-dotnet@v4
        with:
          dontnet-version: "10.0.x"
      - name: Run Test
        run: dotnet  test --configuration Release --verbosity normal
