name: Deploy To Docker

on:
    push:
        branches: ["master"]

jobs:
    init:
        runs-on: ubuntu-latest
        outputs:
          tag: ${{ steps.meta.outputs.tag}}
        steps:
          - uses: actions/checkout@v4
          - name: Generate Tag
            id: meta
            run: |
              TAG="v${GITHUB_RUN_NUMBER}-$(echo $GITHUB_SHA | cut -c1-7)"
              echo "tag=$TAG" >> $GITHUB_OUTPUT

    